services:
  app:
    container_name: password-generator
    image: password-generator-image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
